spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
  h2:
    console:
      enabled: true
      path: /h2-console
server:
  port: 8080
  servlet:
    context-path: /api
mybatis:
  mapper-locations: classpath:mapper/*.xml
